version: '2'
services:
  web-app:
    image: jre8
    container_name: my-web-app
    build: ./app
    ports:
     - "8080:8080"
    volumes:
     - ./app/target:/code
    command: java -jar -Djava.security.egd=file:/dev/./urandom ./code/app-0.0.1-SNAPSHOT.jar
  web-client:
    image: jre8
    container_name: my-web-client
    build: ./client
    volumes:
     - ./client/target:/code
    command: java -jar ./code/client-0.0.1-SNAPSHOT.jar

